In [181]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
import pandas as pd
from sklearn.model_selection import train_test_split

In [182]:
df=pd.DataFrame({"data":["ML is Subset of AI","AI is superset of both ML and DL ML and DL","Gen AI is used to create or generate any type of content "]})
df

                                                data
0                                 ML is Subset of AI
1         AI is superset of both ML and DL ML and DL
2  Gen AI is used to create or generate any type ...

In [183]:
df4=pd.DataFrame({"data1":[" ML is Subset of AI"," AI is superset of both ML and DL ML and DL ","Gen AI is used to create or generate any type of content"]})
df4

                                               data1
0                                 ML is Subset of AI
1        AI is superset of both ML and DL ML and DL
2  Gen AI is used to create or generate any type ...

In [ ]:
model=CountVectorizer()    #binary=True,max_dfe,min_df=1,0.2,max_feature,stopwords="english"--removes unnessery words
#binary--converts like one hot encoder

In [185]:
m=model.fit_transform(df["data"]+df4["data1"])

In [186]:
words=model.get_feature_names_out()  
print(words)
f=m.toarray()
print(f)
df1=pd.DataFrame

['ai' 'and' 'any' 'both' 'content' 'create' 'dl' 'gen' 'generate' 'is'
 'ml' 'of' 'or' 'subset' 'superset' 'to' 'type' 'used']
[[2 0 0 0 0 0 0 0 0 2 2 2 0 2 0 0 0 0]
 [2 4 0 2 0 0 4 0 0 2 4 2 0 0 2 0 0 0]
 [2 0 2 0 2 2 0 2 2 2 0 2 2 0 0 2 2 2]]

In [187]:
model.vocabulary_

{'ml': 10,
 'is': 9,
 'subset': 13,
 'of': 11,
 'ai': 0,
 'superset': 14,
 'both': 3,
 'and': 1,
 'dl': 6,
 'gen': 7,
 'used': 17,
 'to': 15,
 'create': 5,
 'or': 12,
 'generate': 8,
 'any': 2,
 'type': 16,
 'content': 4}

In [ ]:
model3=TfidfVectorizer(min_df=2)  #TF-Term frequency,IDF-Inverse document Frequency

In [189]:
r2=model3.fit_transform(df["data"])

In [190]:
words2=model3.get_feature_names_out()
print(words2)
f2=r.toarray()
print(f2)
df3=pd.DataFrame

['ai' 'is' 'ml' 'of']
[[0.42544054 0.         0.         0.         0.         0.
  0.54783215 0.72033345 0.         0.         0.        ]
 [0.2133645  0.         0.         0.72251501 0.         0.
  0.54949129 0.         0.3612575  0.         0.        ]
 [0.2344005  0.39687454 0.39687454 0.         0.39687454 0.39687454
  0.         0.         0.         0.39687454 0.39687454]]

In [191]:
model2.vocabulary_

{'ml': 6,
 'subset': 7,
 'ai': 0,
 'superset': 8,
 'dl': 3,
 'gen': 4,
 'used': 10,
 'create': 2,
 'generate': 5,
 'type': 9,
 'content': 1}

In [192]:
model2=TfidfVectorizer(stop_words="english")   #stopwords=

In [193]:
r=model2.fit_transform(df["data"])

In [194]:
words1=model2.get_feature_names_out()
print(words1)
f1=r.toarray()
print(f1)
df2=pd.DataFrame

['ai' 'content' 'create' 'dl' 'gen' 'generate' 'ml' 'subset' 'superset'
 'type' 'used']
[[0.42544054 0.         0.         0.         0.         0.
  0.54783215 0.72033345 0.         0.         0.        ]
 [0.2133645  0.         0.         0.72251501 0.         0.
  0.54949129 0.         0.3612575  0.         0.        ]
 [0.2344005  0.39687454 0.39687454 0.         0.39687454 0.39687454
  0.         0.         0.         0.39687454 0.39687454]]

In [195]:
df3=pd.DataFrame(data=f1,columns=words1)
df3

,ai,content,create,dl,gen,generate,ml,subset,superset,type,used
0,0.425441,0.000000,0.000000,0.000000,0.000000,0.000000,0.547832,0.720333,0.000000,0.000000,0.000000
1,0.213365,0.000000,0.000000,0.722515,0.000000,0.000000,0.549491,0.000000,0.361258,0.000000,0.000000
2,0.234400,0.396875,0.396875,0.000000,0.396875,0.396875,0.000000,0.000000,0.000000,0.396875,0.396875