In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,precision_score,recall_score,f1_score,accuracy_score
from sklearn.preprocessing import  OneHotEncoder,StandardScaler,LabelEncoder,RobustScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline

In [2]:
df=pd.read_csv("loan_approval_dataset.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                1000 non-null   int64
 1   Salary             1000 non-null   int64
 2   Credit_Score       1000 non-null   int64
 3   Loan_Amount        1000 non-null   int64
 4   Loan_Term          1000 non-null   object
 5   Employment_Status  1000 non-null   object
 6   Residence_Type     1000 non-null   object
 7   Previous_Default   1000 non-null   object
 8   Loan_Approved      1000 non-null   object
dtypes: int64(4), object(5)
memory usage: 70.4+ KB

In [4]:
df.head()

,Age,Salary,Credit_Score,Loan_Amount,Loan_Term,Employment_Status,Residence_Type,Previous_Default,Loan_Approved
0,56,136748,584,38209,36 months,Employed,Owned,Yes,Yes
1,46,25287,815,27424,24 months,Self-Employed,Rented,No,Yes
2,32,146593,398,42396,12 months,Unemployed,Rented,Yes,Yes
3,60,54387,696,11370,24 months,Unemployed,Owned,No,No
4,25,28512,788,14528,12 months,Employed,Owned,No,No

In [5]:
x=df.drop('Loan_Approved',axis=1)
y=df.Loan_Approved

In [6]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)

**Train data**

In [7]:
num_col=xtrain.select_dtypes(include="number")
obj_col=xtrain.select_dtypes(exclude="number")

In [8]:
encode=OneHotEncoder(sparse_output=False)
obj_encoded_cols=encode.fit_transform(obj_col)
# def num_encoded_concat(df):
#     num_col=xtrain.select_dtypes(include="number")
#     obj_col=xtrain.select_dtypes(exclude="number")
#     encode=OneHotEncoder(sparse_output=False)
#     obj_encoded_cols=encode.fit_transform(obj_col)
#     new_obj_cols=pd.DataFrame(obj_encoded_cols,columns=encode.get_feature_names_out())
#     new_df=pd.concat([num_col.reset_index(drop=True),new_obj_cols.reset_index(drop=True)],axis=1)
#     return new_df

In [9]:
# xtrain=num_encoded_concat(xtrain)
# xtest=num_encoded_concat(xtest)

In [10]:
encode.get_feature_names_out()

array(['Loan_Term_12 months', 'Loan_Term_24 months',
       'Loan_Term_36 months', 'Loan_Term_48 months',
       'Employment_Status_Employed', 'Employment_Status_Self-Employed',
       'Employment_Status_Unemployed', 'Residence_Type_Mortgage',
       'Residence_Type_Owned', 'Residence_Type_Rented',
       'Previous_Default_No', 'Previous_Default_Yes'], dtype=object)

In [11]:
new_obj_cols=pd.DataFrame(obj_encoded_cols,columns=encode.get_feature_names_out())

In [12]:
new_obj_cols

,Loan_Term_12 months,Loan_Term_24 months,Loan_Term_36 months,Loan_Term_48 months,Employment_Status_Employed,Employment_Status_Self-Employed,Employment_Status_Unemployed,Residence_Type_Mortgage,Residence_Type_Owned,Residence_Type_Rented,Previous_Default_No,Previous_Default_Yes
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
1,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
795,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
796,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
797,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
798,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
799,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0

In [13]:
obj_encoded_cols

array([[0., 1., 0., ..., 1., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 0., 1., ..., 1., 1., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]], shape=(800, 12))

In [14]:
new_df=pd.concat([num_col.reset_index(),new_obj_cols.reset_index()],axis=1)

In [15]:
new_df

,index,Age,Salary,Credit_Score,Loan_Amount,index,Loan_Term_12 months,Loan_Term_24 months,Loan_Term_36 months,Loan_Term_48 months,Employment_Status_Employed,Employment_Status_Self-Employed,Employment_Status_Unemployed,Residence_Type_Mortgage,Residence_Type_Owned,Residence_Type_Rented,Previous_Default_No,Previous_Default_Yes
0,29,44,85441,507,17109,0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
1,535,38,87298,489,10776,1,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,695,45,49629,762,39441,2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,557,47,75337,809,40596,3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,836,46,101121,504,31956,4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,106,52,118723,689,31649,795,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
796,270,26,135654,388,22514,796,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
797,860,64,135005,683,8642,797,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
798,435,26,47856,841,45697,798,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
799,102,28,79379,306,11581,799,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0

In [16]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   index                            800 non-null    int64
 1   Age                              800 non-null    int64
 2   Salary                           800 non-null    int64
 3   Credit_Score                     800 non-null    int64
 4   Loan_Amount                      800 non-null    int64
 5   index                            800 non-null    int64
 6   Loan_Term_12 months              800 non-null    float64
 7   Loan_Term_24 months              800 non-null    float64
 8   Loan_Term_36 months              800 non-null    float64
 9   Loan_Term_48 months              800 non-null    float64
 10  Employment_Status_Employed       800 non-null    float64
 11  Employment_Status_Self-Employed  800 non-null    float64
 12  Employment_Status_Unemployed     800 non-null    float64
 13  Residence_Type_Mortgage          800 non-null    float64
 14  Residence_Type_Owned             800 non-null    float64
 15  Residence_Type_Rented            800 non-null    float64
 16  Previous_Default_No              800 non-null    float64
 17  Previous_Default_Yes             800 non-null    float64
dtypes: float64(12), int64(6)
memory usage: 112.6 KB

In [17]:
ytrain

29      No
535     No
695     No
557     No
836    Yes
      ...
106     No
270     No
860     No
435    Yes
102    Yes
Name: Loan_Approved, Length: 800, dtype: object

In [18]:
model =LogisticRegression()    #internally it converts text into numbers.                                                                                                                                                                                                                                       
model.fit(new_df,ytrain)

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [19]:
model =LogisticRegression(max_iter=1000,penalty=None)    #internally it converts text into numbers.                                                                                                                                                                                                                                       
model.fit(new_df,ytrain)
model.coef_

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([[-1.50180231e-04, -6.77785122e-03, -2.30898874e-06,
        -1.92696572e-04,  2.25336634e-06,  8.87849038e-06,
        -8.83873956e-02,  9.39235618e-02,  8.10373800e-02,
         1.66568827e-01,  5.69718922e-02,  2.15099198e-01,
        -1.89287066e-02, -2.05293629e-02,  1.17400987e-01,
         1.56270760e-01,  2.05662178e-01,  4.74801963e-02]])

In [20]:
model =LogisticRegression(max_iter=1000)    #internally it converts text into numbers.                                                                                                                                                                                                                                       
model.fit(new_df,ytrain)
model.coef_

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([[-1.30644553e-04, -7.09598649e-03, -2.31704496e-06,
        -1.87735818e-04,  2.10858644e-06,  1.41977001e-05,
        -8.64631142e-02,  9.29757222e-02,  8.05467512e-02,
         1.64578367e-01,  5.71671667e-02,  2.11724697e-01,
        -1.72541472e-02, -1.92489198e-02,  1.16926894e-01,
         1.53959739e-01,  2.05901991e-01,  4.57357396e-02]])

In [21]:
model =LogisticRegression(max_iter=1000,penalty='l1',solver='liblinear')    #internally it converts text into numbers.                                                                                                                                                                                                                                       
model.fit(new_df,ytrain)
model.coef_

array([[-1.10091423e-04, -6.23880749e-03, -2.17519343e-06,
        -1.08855967e-04,  2.62235940e-06,  3.32099971e-05,
        -1.09674500e-01,  0.00000000e+00,  0.00000000e+00,
         5.92384485e-02,  3.64232012e-02,  2.15949879e-01,
         0.00000000e+00,  0.00000000e+00,  1.10497561e-01,
         1.49722350e-01,  1.48941958e-01,  0.00000000e+00]])

In [22]:
model.score(new_df,ytrain)

0.5475

In [23]:
ypred=model.predict(new_df)

In [24]:
ytrain.value_counts()
''' No-0
yes-1
'''

' No-0\nyes-1\n'

In [25]:
confusion_matrix(ytrain,ypred)

array([[212, 185],
       [177, 226]])

In [26]:
precision_score(ytrain,ypred,pos_label="Yes")

0.5498783454987834

In [27]:
recall_score(ytrain,ypred,pos_label="Yes")

0.5607940446650124

In [28]:
f1_score(ytrain,ypred,pos_label='Yes')

0.5552825552825553

In [29]:
accuracy_score(ytrain,ypred)

0.5475

In [30]:
model.intercept_

array([0.25285694])

In [31]:
model.coef_

array([[-1.10091423e-04, -6.23880749e-03, -2.17519343e-06,
        -1.08855967e-04,  2.62235940e-06,  3.32099971e-05,
        -1.09674500e-01,  0.00000000e+00,  0.00000000e+00,
         5.92384485e-02,  3.64232012e-02,  2.15949879e-01,
         0.00000000e+00,  0.00000000e+00,  1.10497561e-01,
         1.49722350e-01,  1.48941958e-01,  0.00000000e+00]])

In [32]:
ytrain=ytrain.map({"Yes":1,"No":0})
train_data=pd.concat([new_df.reset_index(),ytrain.reset_index()],axis=1)
train_data.drop(['level_0','index'],axis=1)

,Age,Salary,Credit_Score,Loan_Amount,Loan_Term_12 months,Loan_Term_24 months,Loan_Term_36 months,Loan_Term_48 months,Employment_Status_Employed,Employment_Status_Self-Employed,Employment_Status_Unemployed,Residence_Type_Mortgage,Residence_Type_Owned,Residence_Type_Rented,Previous_Default_No,Previous_Default_Yes,Loan_Approved
0,44,85441,507,17109,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0
1,38,87298,489,10776,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0
2,45,49629,762,39441,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0
3,47,75337,809,40596,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0
4,46,101121,504,31956,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,52,118723,689,31649,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0
796,26,135654,388,22514,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0
797,64,135005,683,8642,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0
798,26,47856,841,45697,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1
799,28,79379,306,11581,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1

In [33]:
# features=num_encoded_concat(x)
# y=y.map({"Yes":1,'No':0})
# y

In [34]:
# df=pd.concat([features.reset_index(),y.reset_index()],axis=1)

In [35]:
# df

In [36]:
train_data.corr()['Loan_Approved']

level_0                           -0.003329
index                             -0.016018
Age                               -0.046018
Salary                            -0.050870
Credit_Score                      -0.018104
Loan_Amount                        0.009970
index                             -0.003329
Loan_Term_12 months               -0.038644
Loan_Term_24 months                0.007084
Loan_Term_36 months                0.004536
Loan_Term_48 months                0.027768
Employment_Status_Employed        -0.018542
Employment_Status_Self-Employed    0.047774
Employment_Status_Unemployed      -0.029087
Residence_Type_Mortgage           -0.031755
Residence_Type_Owned               0.010567
Residence_Type_Rented              0.021568
Previous_Default_No                0.042265
Previous_Default_Yes              -0.042265
index                             -0.016018
Loan_Approved                      1.000000
Name: Loan_Approved, dtype: float64

**Test data**

In [37]:
num_col1=xtest.select_dtypes(include="number")
obj_col1=xtest.select_dtypes(exclude="number")

In [38]:
encode1=OneHotEncoder(sparse_output=False)
obj_encoded_cols1=encode1.fit_transform(obj_col1)

In [39]:
encode1.get_feature_names_out()

array(['Loan_Term_12 months', 'Loan_Term_24 months',
       'Loan_Term_36 months', 'Loan_Term_48 months',
       'Employment_Status_Employed', 'Employment_Status_Self-Employed',
       'Employment_Status_Unemployed', 'Residence_Type_Mortgage',
       'Residence_Type_Owned', 'Residence_Type_Rented',
       'Previous_Default_No', 'Previous_Default_Yes'], dtype=object)

In [40]:
new_obj_cols1=pd.DataFrame(obj_encoded_cols1,columns=encode1.get_feature_names_out())

In [41]:
new_obj_cols1

,Loan_Term_12 months,Loan_Term_24 months,Loan_Term_36 months,Loan_Term_48 months,Employment_Status_Employed,Employment_Status_Self-Employed,Employment_Status_Unemployed,Residence_Type_Mortgage,Residence_Type_Owned,Residence_Type_Rented,Previous_Default_No,Previous_Default_Yes
0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
2,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
3,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
196,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
197,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
198,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
199,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [42]:
obj_encoded_cols1

array([[0., 0., 1., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 1., 0., 1.],
       ...,
       [0., 0., 1., ..., 1., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.]], shape=(200, 12))

In [43]:
new_df1=pd.concat([num_col1.reset_index(),new_obj_cols1.reset_index()],axis=1)

In [44]:
new_df1

,index,Age,Salary,Credit_Score,Loan_Amount,index,Loan_Term_12 months,Loan_Term_24 months,Loan_Term_36 months,Loan_Term_48 months,Employment_Status_Employed,Employment_Status_Self-Employed,Employment_Status_Unemployed,Residence_Type_Mortgage,Residence_Type_Owned,Residence_Type_Rented,Previous_Default_No,Previous_Default_Yes
0,521,25,48769,586,29322,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
1,737,38,109431,311,25447,1,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
2,740,34,128730,717,34336,2,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
3,660,38,60998,821,10355,3,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,411,61,98757,680,31421,4,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,408,54,136243,448,43975,195,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
196,332,34,146944,719,47138,196,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
197,208,40,21645,319,6875,197,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
198,613,22,90342,734,42291,198,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
199,78,40,54016,415,14885,199,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [45]:
new_df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 18 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   index                            200 non-null    int64
 1   Age                              200 non-null    int64
 2   Salary                           200 non-null    int64
 3   Credit_Score                     200 non-null    int64
 4   Loan_Amount                      200 non-null    int64
 5   index                            200 non-null    int64
 6   Loan_Term_12 months              200 non-null    float64
 7   Loan_Term_24 months              200 non-null    float64
 8   Loan_Term_36 months              200 non-null    float64
 9   Loan_Term_48 months              200 non-null    float64
 10  Employment_Status_Employed       200 non-null    float64
 11  Employment_Status_Self-Employed  200 non-null    float64
 12  Employment_Status_Unemployed     200 non-null    float64
 13  Residence_Type_Mortgage          200 non-null    float64
 14  Residence_Type_Owned             200 non-null    float64
 15  Residence_Type_Rented            200 non-null    float64
 16  Previous_Default_No              200 non-null    float64
 17  Previous_Default_Yes             200 non-null    float64
dtypes: float64(12), int64(6)
memory usage: 28.3 KB

In [46]:
ytest

521     No
737    Yes
740     No
660    Yes
411    Yes
      ...
408     No
332     No
208     No
613    Yes
78     Yes
Name: Loan_Approved, Length: 200, dtype: object

In [47]:
model =LogisticRegression()                                                                                                                                                                                                                                          
model.fit(new_df1,ytest)

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [48]:
model.score(new_df1,ytest)

0.6

In [49]:
ytest=ytest.map({"Yes":1,"No":0})
test_data=pd.concat([new_df1.reset_index(),ytest.reset_index()],axis=1)
test_data.drop(['level_0','index'],axis=1)

,Age,Salary,Credit_Score,Loan_Amount,Loan_Term_12 months,Loan_Term_24 months,Loan_Term_36 months,Loan_Term_48 months,Employment_Status_Employed,Employment_Status_Self-Employed,Employment_Status_Unemployed,Residence_Type_Mortgage,Residence_Type_Owned,Residence_Type_Rented,Previous_Default_No,Previous_Default_Yes,Loan_Approved
0,25,48769,586,29322,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0
1,38,109431,311,25447,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1
2,34,128730,717,34336,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0
3,38,60998,821,10355,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1
4,61,98757,680,31421,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,54,136243,448,43975,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0
196,34,146944,719,47138,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0
197,40,21645,319,6875,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0
198,22,90342,734,42291,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1
199,40,54016,415,14885,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1

In [50]:
test_data.corr()['Loan_Approved']

level_0                            0.000087
index                             -0.012525
Age                                0.090303
Salary                            -0.168937
Credit_Score                       0.022670
Loan_Amount                        0.153329
index                              0.000087
Loan_Term_12 months                0.013380
Loan_Term_24 months                0.018755
Loan_Term_36 months               -0.054061
Loan_Term_48 months                0.026799
Employment_Status_Employed         0.090385
Employment_Status_Self-Employed   -0.248984
Employment_Status_Unemployed       0.154125
Residence_Type_Mortgage           -0.058406
Residence_Type_Owned               0.054623
Residence_Type_Rented              0.006341
Previous_Default_No                0.001018
Previous_Default_Yes              -0.001018
index                             -0.012525
Loan_Approved                      1.000000
Name: Loan_Approved, dtype: float64

**Column Transformer : we can apply 2 or 3 preprocessing technique together,it reduces number of steps.**
simple imputer handles missing values

In [51]:
from sklearn.compose import ColumnTransformer

In [52]:
# compose=ColumnTransformer(transformers=[
#     ('name of preprocessing method',Instance of preprocessing like -->StandardScaler(),column names),
#     ('name of preprocessing method',Instance of preprocessing like -->OneHotEncoder(),column names)
#     ('name of preprocessing method',Instance of preprocessing like -->PolynomialFeatures(),column names)
# ])  #syntax

In [53]:
num_col=x.select_dtypes(include='number').columns
obj_col=x.select_dtypes(exclude='number').columns

In [54]:
num_col

Index(['Age', 'Salary', 'Credit_Score', 'Loan_Amount'], dtype='object')

In [55]:
compose=ColumnTransformer(transformers=[('scaling',StandardScaler(),num_col),('encoding',OneHotEncoder(),obj_col)])

In [56]:
compose.fit_transform(df)

array([[ 1.11288175,  1.35351736,  0.04865542, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.3716524 , -1.57299909,  1.51383627, ...,  1.        ,
         1.        ,  0.        ],
       [-0.6660687 ,  1.61200737, -1.13110059, ...,  1.        ,
         0.        ,  1.        ],
       ...,
       [-1.03668337, -0.54161215, -1.75269246, ...,  1.        ,
         0.        ,  1.        ],
       [ 1.48349643, -1.40343805, -0.54756536, ...,  0.        ,
         1.        ,  0.        ],
       [-1.62966685, -1.0283978 ,  1.51383627, ...,  0.        ,
         0.        ,  1.        ]], shape=(1000, 16))

In [57]:
compose=ColumnTransformer(transformers=[('scaling',StandardScaler(),num_col),('encoding',OneHotEncoder(),obj_col)],remainder='drop') #drop-it removes the target columns
compose.fit_transform(df)

array([[ 1.11288175,  1.35351736,  0.04865542, ...,  0.        ,
         0.        ,  1.        ],
       [ 0.3716524 , -1.57299909,  1.51383627, ...,  1.        ,
         1.        ,  0.        ],
       [-0.6660687 ,  1.61200737, -1.13110059, ...,  1.        ,
         0.        ,  1.        ],
       ...,
       [-1.03668337, -0.54161215, -1.75269246, ...,  1.        ,
         0.        ,  1.        ],
       [ 1.48349643, -1.40343805, -0.54756536, ...,  0.        ,
         1.        ,  0.        ],
       [-1.62966685, -1.0283978 ,  1.51383627, ...,  0.        ,
         0.        ,  1.        ]], shape=(1000, 16))

In [58]:
compose=ColumnTransformer(transformers=[('scaling',StandardScaler(),num_col),('encoding',OneHotEncoder(),obj_col)],remainder='passthrough') #passthrough-it passes  the target columns
compose.fit_transform(df)

array([[1.1128817500082018, 1.3535173637964144, 0.04865542121409337, ...,
        0.0, 1.0, 'Yes'],
       [0.37165239739850314, -1.5729990872839834, 1.5138362712278461,
        ..., 1.0, 0.0, 'Yes'],
       [-0.666068696255075, 1.6120073689182643, -1.1311005878878893, ...,
        0.0, 1.0, 'Yes'],
       ...,
       [-1.0366833725599243, -0.5416121516621948, -1.7526924636512995,
        ..., 0.0, 1.0, 'Yes'],
       [1.483496426313051, -1.4034380458338152, -0.5475653575793817, ...,
        1.0, 0.0, 'Yes'],
       [-1.6296668546476831, -1.028397798686989, 1.5138362712278461, ...,
        0.0, 1.0, 'No']], shape=(1000, 17), dtype=object)

In [59]:
compose=ColumnTransformer(transformers=[('scaling',StandardScaler(),num_col),('encoding',LabelEncoder(),'Loan_Approved')],remainder='drop') #drop-it removes the target columns
# compose.fit_transform(df)

In [60]:
# xtrain.compose.fit_transfor(xtrain)
# xtest.compose.transform(xtest)